import test from 'node:test';
import assert from 'node:assert/strict';
import {agendaDates,composeProfessionalAgenda,sendDailyProfessionalAgenda,AGENDA_TEMPLATE_BODY} from '../review/medinet-professional-agenda.js';
const now=new Date('2026-09-14T11:05:00Z');
const appointment=(id,day,status='Agendado',name='Profesional')=>({id,fecha:day,hora:'10:00',estado:{nombre:status},profesional:{nombres:name,paterno:'Prueba'},paciente:{nombres:'Paciente de prueba'},tipo:'Consulta',sucursal:{id:2,nombre:'Sede'}});
test('agenda includes only the intended professional, today/tomorrow and active appointments',()=>{assert.deepEqual(agendaDates(new Date('2026-09-30T15:00:00Z')),['2026-09-30','2026-10-01']);const r=composeProfessionalAgenda([appointment(1,'2026/09/14'),appointment(2,'2026/09/15'),appointment(3,'2026/09/14','Cancelada'),appointment(4,'2026/09/14','Agendado','Otro')],'Profesional Prueba',now);assert.match(r.message,/Hoy 2026-09-14: 1 citas/);assert.match(r.message,/Mañana 2026-09-15: 1 citas/);assert.doesNotMatch(r.message,/Otro/);});
const env={MEDINET_AGENDA_SEND_ENABLED:'true',MEDINET_AGENDA_PROFESSIONAL:'Profesional Prueba',MEDINET_AGENDA_PHONE:'+56900000000',MEDINET_AGENDA_CONVERSATION_ID:'7',MEDINET_AGENDA_INBOX_ID:'9',MEDINET_AGENDA_TEMPLATE:'agenda_profesional_test',CHATWOOT_API_TOKEN:'synthetic'};
function setup({mismatch=false,unknown=false,template=true}={}){let reserved=false,sends=0;const pool={query:async(sql)=>{if(sql.startsWith('INSERT')){const rowCount=reserved?0:1;reserved=true;return{rowCount};}return{rows:[]};}};const http=async(url,options)=>{if(options.method==='POST'){sends++;if(unknown)throw Error('network timeout');return Response.json({id:123});}if(url.endsWith('/inboxes/9'))return Response.json({message_templates:[{name:env.MEDINET_AGENDA_TEMPLATE,language:'es_CL',status:template?'APPROVED':'PENDING',category:'UTILITY',components:[{type:'BODY',text:AGENDA_TEMPLATE_BODY}]}]});return Response.json({inbox_id:9,meta:{sender:{phone_number:mismatch?'+56900000001':env.MEDINET_AGENDA_PHONE}}});};return{pool,http,sends:()=>sends};}
test('disabled or unverified destinations and templates cannot send',async()=>{let h=setup();assert.equal((await sendDailyProfessionalAgenda({...h,env:{},now})).status,'disabled');h=setup({mismatch:true});assert.equal((await sendDailyProfessionalAgenda({...h,env,now})).status,'recipient_mismatch');assert.equal(h.sends(),0);h=setup({template:false});assert.equal((await sendDailyProfessionalAgenda({...h,env,now})).status,'template_unverified');assert.equal(h.sends(),0);});
test('one durable send per recipient/day, including uncertain network outcomes',async()=>{for(const unknown of [false,true]){const h=setup({unknown}),args={...h,env,now,appointments:async()=>[]};assert.equal((await sendDailyProfessionalAgenda(args)).status,unknown?'uncertain':'accepted');assert.equal((await sendDailyProfessionalAgenda(args)).status,'already_attempted');assert.equal(h.sends(),1);}});
