import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {JSDOM}=await import(process.env.REVIEW_TEST_JSDOM_PATH);
const code=await readFile(new URL('../review/site/medinet-daily.js',import.meta.url),'utf8');
const response={items:[{id:'1',patient:'<script>bad</script>',time:'09:00',professional:'Profesional Prueba',professionalKey:'profesional prueba',branchId:'2',branch:'Sede',typeId:'3',type:'Consulta',status:'Confirmado',confirmation:'Confirmada en Medinet',expectedAmount:null,phone:'+56900000000',email:'example@example.test',conversationUrl:null}],professionals:[{key:'profesional prueba',name:'Profesional Prueba',branchId:'2',branch:'Sede',occupied:1,confirmed:1,free:null,blocked:null,expectedKnown:0,missingTariffs:1}],syncedAt:new Date().toISOString(),slotsFresh:false,limitations:['Sin pagos conectados']};
const tick=()=>new Promise(r=>setTimeout(r,0));
function setup(){const dom=new JSDOM('<section id="tab-daily-agenda"></section><section id="tab-daily-report"></section>',{url:'https://example.test',runScripts:'outside-only'});dom.window.eval(code);return dom;}
test('daily UI disables every date/filter control while loading and displays failures explicitly',async()=>{const d=setup();try{let release;d.window.fetch=()=>new Promise(r=>release=r);d.window.loadDailyMedinet('daily-agenda');assert.ok([...d.window.document.querySelectorAll('input,select,button')].every(e=>e.disabled));release(Response.json({error:'Medinet no disponible'},{status:503}));await tick();assert.match(d.window.document.body.textContent,/Medinet no disponible.*Actualizar/);assert.ok([...d.window.document.querySelectorAll('input,select,button')].every(e=>!e.disabled));}finally{d.window.close();}});
test('report renders escaped data, preserves unknown cash values and supports professional filtering',async()=>{const d=setup();try{d.window.fetch=async()=>Response.json(response);d.window.loadDailyMedinet('daily-report');await tick();assert.equal(d.window.document.querySelectorAll('script').length,0);assert.match(d.window.document.body.textContent,/<script>bad<\/script>/);assert.match(d.window.document.body.textContent,/Sin integración/);const s=d.window.document.querySelectorAll('select')[1];s.value='profesional prueba';s.dispatchEvent(new d.window.Event('change'));assert.match(d.window.document.body.textContent,/Preparar mensaje de agenda/);assert.equal(d.window.document.querySelector('a').href,'tel:+56900000000');}finally{d.window.close();}});
